USE ESCUELA2;
-- LE PONGO ALIAS A LA TABLA ALUMNO (A) Y PIDO INFORMACION DE TODOS LOS ALUMNOS QUE CURSEN LA CARRERA 4
SELECT * FROM ALUMNO AS A 
WHERE A.ALU_CARRERA=4;

use ESCUELA2;
/* SELECCIONO LAS COLUMNAS ALU_ID ALU_NAME Y CARR_NAME USANDO JOIN PARA SABER QUE CARRERA CURSAN LOS AMNUNOS*/
SELECT a.ALU_ID, a.ALU_NAME, C.CARR_NAME FROM ALUMNO AS A
INNER JOIN CARRERA AS C ON A.ALU_CARRERA=C.CARR_ID;

USE ESCUELA2;
/* SELECCIONO TODO DE ALUMNO Y CARRERA */
SELECT * FROM ALUMNO;
SELECT * FROM CARRERA;


USE ESCUELA2;
SELECT MA_NAME FROM MATERIA_ALUMNO AS MA
JOIN ALUMNO AS A ON MA.MA_ALUMNO_ID=A.ALU_ID;