USE ESCUELA2;
-- LE PONGO ALIAS A LA TABLA ALUMNO (A) Y PIDO INFORMACION DE TODOS LOS ALUMNOS QUE CURSEN LA CARRERA 4
SELECT * FROM ALUMNO AS A 
WHERE A.ALU_CARRERA=4;

use ESCUELA2;
/* SELECCIONO LAS COLUMNAS ALU_ID ALU_NAME Y CARR_NAME USANDO JOIN PARA SABER QUE CARRERA CURSAN LOS AMNUNOS*/
SELECT a.ALU_ID, a.ALU_NAME, C.CARR_NAME
FROM ALUMNO AS A
INNER JOIN CARRERA AS C ON A.ALU_CARRERA=C.CARR_ID;


/* ADEMAS LE AGREGO LA MATERIA QUE ESTA CURSANDO
, SOLO SE PUEDE PORQUE HAGO UNA CONCECCION PREVIA CON MATERIA 
ALUMNO QUE ES EL PUENTE CON LA TABLA MATERIA */
USE ESCUELA2;
SELECT a.ALU_ID, a.ALU_NAME, C.CARR_NAME, MA.MA_ID, M.MAT_NAME FROM ALUMNO AS A
INNER JOIN CARRERA AS C ON A.ALU_CARRERA=C.CARR_ID
INNER JOIN MATERIA_ALUMNO AS MA ON A.ALU_ID=MA.MA_ID
INNER JOIN MATERIA AS M ON MA.MA_MATERIA_ID=M.MAT_ID;

/* LO MISMO PERO CON FILTRO ALUMNOS CON EDAD DE 22 */
USE ESCUELA2;
SELECT a.ALU_ID, a.ALU_NAME, C.CARR_NAME, M.MAT_ID, M.MAT_NAME FROM ALUMNO AS A
INNER JOIN CARRERA AS C ON A.ALU_CARRERA=C.CARR_ID
INNER JOIN MATERIA_ALUMNO AS MA ON A.ALU_ID=MA.MA_ID
INNER JOIN MATERIA AS M ON MA.MA_MATERIA_ID=M.MAT_ID
WHERE ALU_EDAD=22;

USE ESCUELA2;
SELECT * FROM ALUMNO;

USE ESCUELA2;
SELECT * FROM MATERIA;

USE ESCUELA2;
/* SELECCIONO TODO DE ALUMNO Y CARRERA */
SELECT * FROM ALUMNO;
SELECT * FROM CARRERA;


USE ESCUELA2;
SELECT MA_NAME FROM MATERIA_ALUMNO AS MA
JOIN ALUMNO AS A ON MA.MA_ALUMNO_ID=A.ALU_ID;


USE ESCUELA2;
UPDATE 