DROP DATABASE ESCUELA2;
CREATE DATABASE ESCUELA2;
USE ESCUELA2;

CREATE TABLE MATERIA(
    MAT_ID INT ,
    MAT_NAME VARCHAR(40),
    MAT_CREDITOS VARCHAR(40),
    CONSTRAINT PK_MAT PRIMARY KEY (MAT_ID)
);

CREATE TABLE CARRERA(
    CARR_ID INT,
    CARR_NAME VARCHAR(40),
    CARR_DURACION FLOAT,
    CONSTRAINT PK_CARR PRIMARY KEY(CARR_ID)
);

CREATE TABLE PROFESOR(
    PRO_ID INT,
    PRO_NAME VARCHAR(40),
    PRO_DIRECCION VARCHAR(49),
    PRO_TELEFONO BIGINT,
    PRO_HORARIO DATETIME,
    CONSTRAINT PK_PRO PRIMARY KEY (PRO_ID)
);


CREATE TABLE ALUMNO(
    ALU_ID INT,
    ALU_NAME VARCHAR(30),
    ALU_EDAD INT,
    ALU_SEMESTRE INT,
    ALU_GENERO VARCHAR(10),
    ALU_CARRERA INT,
    CONSTRAINT PK_ALU PRIMARY KEY (ALU_ID),
    CONSTRAINT FK_ALU FOREIGN KEY (ALU_CARRERA) REFERENCES CARRERA(CARR_ID)
);

CREATE TABLE ALUMNO_PROFESOR(
    AP_ID INT,
    AP_ALUMNO_ID INT,
    AP_PROFESOR_ID INT,
    CONSTRAINT PK_AP PRIMARY KEY (AP_ID),
    CONSTRAINT FK_AP_AL FOREIGN KEY (AP_ALUMNO_ID) REFERENCES ALUMNO(ALU_ID),
    CONSTRAINT FK_AP_PRO FOREIGN KEY (AP_PROFESOR_ID) REFERENCES PROFESOR(PRO_ID)
);

CREATE TABLE MATERIA_ALUMNO(
    MA_ID INT,
    MA_ALUMNO_ID INT,
    MA_MATERIA_ID INT,
    CONSTRAINT PK_MA PRIMARY KEY (MA_ID),
    CONSTRAINT FK_MA_ALU FOREIGN KEY (MA_ALUMNO_ID) REFERENCES ALUMNO(ALU_ID),
    CONSTRAINT FK_MA_MAT FOREIGN KEY (MA_MATERIA_ID) REFERENCES MATERIA(MAT_ID)

);

CREATE TABLE MATERIA_PROFESOR(
    MP_ID INT,
    MP_MATERIA_ID INT,
    MP_PROFESOR_ID INT,
    CONSTRAINT PK_MP PRIMARY KEY (MP_ID),
    CONSTRAINT FK_MP_MAT FOREIGN KEY (MP_MATERIA_ID) REFERENCES MATERIA(MAT_ID),
    CONSTRAINT FK_MP_PRO FOREIGN KEY (MP_PROFESOR_ID) REFERENCES PROFESOR(PRO_ID)

)


USE ESCUELA2;
DELETE FROM * CARRERA;

INSERT INTO ESCUELA2.CARRERA VALUES (1, 'DESARROLLO DE SOFWARE', 3)
INSERT INTO ESCUELA2.CARRERA VALUES (2, 'PROFESORADO DE MATEMATICAS', 3);
INSERT INTO ESCUELA2.CARRERA VALUES (3, 'PROFESORADO DE HISTORIA', 4);
INSERT INTO ESCUELA2.CARRERA VALUES (4, 'PROFESOR INCIAL', 3);
INSERT INTO ESCUELA2.CARRERA VALUES (5, 'FISICA', 4);

INSER INTO 

SELECT * FROM ESCUELA2.CARRERA;
