/* DDL */

CREATE DATABASE MUEBLERIA;

USE MUEBLERIA;

CREATE TABLE TIPO_MUEBLES(
    TMU_ID INT AUTO_INCREMENT,
    TMU_NAME VARCHAR(100),
    CONSTRAINT PK_TMU  PRIMARY KEY (TMU_ID)
);

CREATE TABLE TIPO_MADERA(
    TMA_ID INT AUTO_INCREMENT,
    TMA_NAME VARCHAR(100),
    CONSTRAINT PK_TMA PRIMARY KEY (TMA_ID)
);

CREATE TABLE NOMBRE_MUEBLE(
    NMU_ID INT AUTO_INCREMENT,
    NMU_NAME VARCHAR(100),
    CONSTRAINT PK_NMU PRIMARY KEY (NMU_ID)
);

CREATE TABLE PROVEDORES(
    PRO_ID INT AUTO_INCREMENT,
    PRO_NAME VARCHAR(100),
    CONSTRAINT PRO_PK PRIMARY KEY (PRO_ID)
);

CREATE TABLE DETALLE_MUEBLE(
    DMU_ID INT AUTO_INCREMENT,
    DMU_NOMBRE_MUEBLE_ID INT,
    DMU_TIPO_MADERA_ID INT,
    DMU_TIPO_MUEBLE_ID INT,
    CONSTRAINT PK_DMU PRIMARY KEY (DMU_ID),
    FOREIGN KEY (DMU_NOMBRE_MUEBLE_ID) REFERENCES NOMBRE_MUEBLE(NMU_ID),
    FOREIGN KEY (DMU_TIPO_MADERA_ID) REFERENCES TIPO_MADERA(TMA_ID),
    FOREIGN KEY (DMU_TIPO_MUEBLE_ID) REFERENCES TIPO_MUEBLES(TMU_ID) 
);

CREATE TABLE VENTAS_MINORISTA(
    VM_ID INT AUTO_INCREMENT,
    VM_DETALLE_MUEBLE INT,
    VM_CANTIDAD INT,
    CONSTRAINT PK_VM PRIMARY KEY (VM_ID),
    FOREIGN KEY (VM_DETALLE_MUEBLE) REFERENCES DETALLE_MUEBLE(DMU_ID)
);

CREATE TABLE COMPRAS_MAYORISTA(
    CM_ID INT AUTO_INCREMENT,
    CM_PROVEDORES_ID INT,
    CM_DETALLE_MUEBLE_ID INT,
    CM_CANTIDAD INT,
    CONSTRAINT PK_CM PRIMARY KEY (CM_ID),
    FOREIGN KEY (CM_PROVEDORES_ID) REFERENCES PROVEDORES(PRO_ID),
    FOREIGN KEY (CM_DETALLE_MUEBLE_ID) REFERENCES DETALLE_MUEBLE(DMU_ID)
);

CREATE TABLE COMPRAS_VENTAS(
    CV_ID INT AUTO_INCREMENT,
    CV_COMPRAS_MAYORISTAS_ID INT,
    CV_VENTAS_MINORISTAS_ID INT,
    CV_RESTA_SUMA INT,
    CONSTRAINT PK_CV PRIMARY KEY (CV_ID),
    FOREIGN KEY (CV_COMPRAS_MAYORISTAS_ID) REFERENCES COMPRAS_MAYORISTA(CM_ID),
    FOREIGN KEY (CV_VENTAS_MINORISTAS_ID) REFERENCES VENTAS_MINORISTA(VM_ID)
);

CREATE TABLE STOCK(
    ST_ID INT AUTO_INCREMENT,
    ST_COMPRAS_VENTAS_ID INT,
    CONSTRAINT PK_STOCK PRIMARY KEY (ST_ID),
    FOREIGN KEY (ST_COMPRAS_VENTAS_ID) REFERENCES COMPRAS_VENTAS(CV_ID)
);
