// NOS PERMITE USAR UNA FUNCION PURA
// SIGNIFICA QUE NO VA A TENER EFECTOS SECUNDARIOS
// INTERNAMENTE HACE SU PROGRAMACION
// una funcion reductora retorna un estado

export const TYPES={
    INCREMENT:"INCREMENT",
    INCREMENT_4:"INCREMENT_4",
    DECREMENT:"DECREMENT",
    DECREMENT_4:"DECREMENT_4",
    RESET:"RESET"

}