/* DML MUEBLERIA */

INSERT INTO MUEBLERIA.TIPO_MUEBLES ( TMU_NAME) VALUES ('SILLA');
INSERT INTO MUEBLERIA.TIPO_MUEBLES ( TMU_NAME) VALUES ('MESA');
INSERT INTO MUEBLERIA.TIPO_MUEBLES ( TMU_NAME) VALUES ('CAMA');
INSERT INTO MUEBLERIA.TIPO_MUEBLES ( TMU_NAME) VALUES ('SILLON');

SELECT * FROM MUEBLERIA.TIPO_MUEBLES
WHERE TMU_NAME='CAMA';
 
INSERT INTO MUEBLERIA.TIPO_MADERA (TMA_NAME) VALUES ('PINO');
INSERT INTO MUEBLERIA.TIPO_MADERA (TMA_NAME) VALUES ('SAUCE');
INSERT INTO MUEBLERIA.TIPO_MADERA (TMA_NAME) VALUES ('ALGARROBO');
INSERT INTO MUEBLERIA.TIPO_MADERA (TMA_NAME) VALUES ('MELAMINA');


INSERT INTO MUEBLERIA.NOMBRE_MUEBLE (NMU_NAME) VALUES ('GAMER');
INSERT INTO MUEBLERIA.NOMBRE_MUEBLE (NMU_NAME) VALUES ('PARAISO');
INSERT INTO MUEBLERIA.NOMBRE_MUEBLE (NMU_NAME) VALUES ('COMUNACHA');
INSERT INTO MUEBLERIA.NOMBRE_MUEBLE (NMU_NAME) VALUES ('CURVO');

INSERT INTO MUEBLERIA.PROVEDORES (PRO_NAME) VALUES ('SCALONI');
INSERT INTO MUEBLERIA.PROVEDORES (PRO_NAME) VALUES ('DEPAUL');
INSERT INTO MUEBLERIA.PROVEDORES (PRO_NAME) VALUES ('MESSI');
INSERT INTO MUEBLERIA.PROVEDORES (PRO_NAME) VALUES ('SAMUEL');

/* OTRO TIPO DE INSERT PERO NO RECONOCE EL AUTO_INCREMENT (RESPETA EL ORDEN DE LA TABLA, UTIL PARA NO ACORDARSE EL NOMBRE EXACTO DE LA TABLA) */
INSERT INTO MUEBLERIA.DETALLE_MUEBLE VALUES (1, 2, 3, 4);
INSERT INTO MUEBLERIA.DETALLE_MUEBLE VALUES (2, 3, 2, 1);
INSERT INTO MUEBLERIA.DETALLE_MUEBLE VALUES (3, 4, 1, 2);
INSERT INTO MUEBLERIA.DETALLE_MUEBLE VALUES (4, 1, 3, 1);

INSERT INTO MUEBLERIA.VENTAS_MINORISTA VALUES (1, 2, 3);
INSERT INTO MUEBLERIA.VENTAS_MINORISTA VALUES (2, 1, 20);
INSERT INTO MUEBLERIA.VENTAS_MINORISTA VALUES (3, 1, 31);
INSERT INTO MUEBLERIA.VENTAS_MINORISTA VALUES (4, 1, 7);

INSERT INTO MUEBLERIA.COMPRAS_MAYORISTA VALUES (1, 1, 2, 8);
INSERT INTO MUEBLERIA.COMPRAS_MAYORISTA VALUES (2, 1, 3, 10);
INSERT INTO MUEBLERIA.COMPRAS_MAYORISTA VALUES (3, 1, 1, 210);
INSERT INTO MUEBLERIA.COMPRAS_MAYORISTA VALUES (4, 1, 4, 121);

INSERT INTO MUEBLERIA.COMPRAS_VENTAS VALUES (1, 2, 3, 4);
INSERT INTO MUEBLERIA.COMPRAS_VENTAS VALUES (2, 2, 3, 4);
INSERT INTO MUEBLERIA.COMPRAS_VENTAS VALUES (3, 2, 3, 4);
INSERT INTO MUEBLERIA.COMPRAS_VENTAS VALUES (4, 2, 3, 4);

INSERT INTO MUEBLERIA.STOCK VALUES (1, 3);
INSERT INTO MUEBLERIA.STOCK VALUES (2, 2);
INSERT INTO MUEBLERIA.STOCK VALUES (3, 2);
INSERT INTO MUEBLERIA.STOCK VALUES (4, 1);

USE MUEBLERIA;
SELECT * FROM MUEBLERIA.DETALLE_MUEBLE
WHERE DMU_TIPO_MADERA_ID=3;

SELECT * FROM  MUEBLERIA.COMPRAS_VENTAS
WHERE CV_RESTA_SUMA=4 AND CV_ID=1;

DROP DATABASE MUEBLERIA;

